services:
  db:
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nextcloud
    image: mysql:8.0.32
    ports:
      - "3306:3306"
  # To start with a populated database, mount an SQL file
  #  volumes:
  #    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nextcloud:
    depends_on:
      - db
    environment:
      - MARIADB_ROOT_PASSWORD=nextcloud
      - MYSQL_HOST=db
    expose:
      - 443
    image: ghcr.io/pdsinterop/solid-nextcloud:main-30
    ports:
      - "443:443"
    volumes:
      - ./solid/:/var/www/html/apps/solid/
      - ./site.conf:/etc/apache2/sites-enabled/000-default.conf

  pubsub:
    depends_on:
      - nextcloud
    expose:
      - 8080
    image: ghcr.io/pdsinterop/php-solid-pubsub-server
    ports:
      - "8080:8080"