---
name: Security check

on:
  - push
  - pull_request
  # Allow manually triggering the workflow.
  - workflow_dispatch

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-check:
    runs-on: ubuntu-latest
    name: "Security check"

    strategy:
      matrix:
        php: ['8.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
        with:
          working-directory: "solid"

      - name: Download security checker
        # yamllint disable-line rule:line-length
        run: wget -P . https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.4/local-php-security-checker_2.0.4_linux_amd64

      - name: Make security checker executable
        run: chmod +x ./local-php-security-checker_2.0.4_linux_amd64

      - name: Check against insecure dependencies
        run: ./local-php-security-checker_2.0.4_linux_amd64 --path=solid/composer.lock
