---
name: Quality Assurance jobs

on:
  - push
  - pull_request

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "docker://composer"
        with:
          args: composer validate --strict --working-dir=solid/

  php-codesniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pipeline-components/php-codesniffer@master
        with:
          options: --standard=build/phpcs.xml.dist
